#!/bin/zsh

# Ensure XDG folders are set
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CODE_HOME="$HOME/.local/src"

export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="brave"

export MANPAGER='nvim +Man!'
export MANWIDTH=999

export PAGER=less

# Fix XDG compliance (https://wiki.archlinux.org/index.php/XDG_Base_Directory)
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password_store"
export GOPASS_CONFIG="$XDG_CONFIG_HOME/gopass/config.yml"
export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

export SHORT_HOST=${HOST/.*/}
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"

export LESS=-R
export LESSHISTFILE="-"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"

export DOTFILES_HOME="${XDG_CODE_HOME:-$HOME/.local/src}/github.com/0x6a68/echo-boomer-rice.git"

export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

export GPG_TTY=$(tty)
export PINENTRY_USER_DATA=qt

[ "$(tty)" = "/dev/tty1" ] && ! ps -e | grep -qw Xorg && exec startx
