#!/bin/sh

dbus-update-activation-environment \
	--systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources

mpd &
sxhkd &
xss-lock slock &
multi-head &
dunst &
bluetoothctl power on &
xset r rate 300 50 &
xset +dpms &
xset dpms 0 0 900 &
