#!/bin/sh

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
xrdbpid=$! # Uncomment to use Xresources colors/settings on startup

autostart="multi-head power-management vpn-management"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources
