root:
  askformore: false
  autoclip: false
  autoprint: false
  autoimport: false
  autosync: false
  check_recipient_hash: false
  cliptimeout: 0
  concurrency: 1
  editrecipients: false
  exportkeys: false
  nocolor: false
  noconfirm: false
  nopager: false
  notifications: false
  path: gpgcli-gitcli-fs+file:///home/jhh/.local/share/password_store
  recipient_hash: {}
  safecontent: true
  usesymbols: true
mounts: {}
