#!/bin/sh

dbus-update-activation-environment \
	--systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources

mpd &
configure_xset &
xss-lock slock &
multi-head &
bluetoothctl power on &
