-- vim.opt.termguicolors = true
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.autocommands")
require("user.commands")
require("user.colorscheme")
require("user.cmp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.lualine")
require("user.toggleterm")
require("user.impatient")
require("user.illuminate")
require("user.lsp")
require("user.neotest")
require("user.dap")
require("user.harpoon")
-- require("user.marks")
